spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hellodb
    username: user
    password: password
  liquibase:
    enabled: true
  sql:
    init:
      mode: always
server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    com.dora.assignment.repository: debug
