spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/hellodb
    username: user
    password: password
  liquibase:
    enabled: true
  sql:
    init:
      mode: always
  profiles:
    active: ${APP_PROFILE:internal}
server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT:8080}
logging:
  level:
    com.dora.assignment.repository: debug
    com.dora.assignment.service: debug


dora:
  assignment:
    web-client:
      url: https://google-translate1.p.rapidapi.com/language/translate/v2
      headers:
        - name: Content-Type
          value: application/x-www-form-urlencoded
        - name: Accept-Encoding
          value: application/gzip
        - name: X-RapidAPI-Key
          value: ebf8eecadbmsh4e7b2cd6aab9cb3p19c03ajsnf4ab1650874e
        - name: X-RapidAPI-Host
          value: google-translate1.p.rapidapi.com
